# Generated by Django 6.0 on 2026-01-17 18:22

import django.db.models.deletion
import vpm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(max_length=100)),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='vpm.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDescription', models.TextField()),
                ('ProductPrice', models.CharField(max_length=50)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to=vpm.models.rename_image)),
                ('CategoryName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vpm.category')),
                ('SubCategoryName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vpm.subcategory')),
            ],
        ),
    ]
