# Generated by Django 6.0 on 2026-01-07 23:22

import vpm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductPrice',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(upload_to=vpm.models.rename_image),
        ),
    ]
